2차 엔티티 구현 사항입니다.
Ustroytelling/us-server pull request #3
Opened 2023-11-08 13:47 UTC by dujong

### 구현목록
- 유저(User)
- 접근권한(Authority)
- 좋아요(NovelLike, ParagraphLike, ChapterCommentLike)
- 댓글(NovelComment, ChapterComment)

### 수정목록
- 각 Entity @Column id 값 추가
- Entity 개발로 인한 추가 연관관계 설정

2023-11-08 14:05 UTC, YEONGORI requested changes
코드리뷰 완료하였습니다. 일관성을 위해 몇가지만 수정 부탁드립니다!

2023-11-08 14:05 UTC, YEONGORI commented on src/main/java/us/usserver/like/NovelLike.java
> +    @Column(name = "novelLike_id")
### 수정 요청
column 명에 일관성이 흐트러진 것 같습니다.

novel_like_id로 수정이 되어야 할 것 같습니다!
`@Column(name = "novel_like_id")`

2023-11-08 14:05 UTC, YEONGORI commented on src/main/java/us/usserver/like/ParagraphLike.java
> +    @Column(name = "paragraphLike_id")
### 수정 요청
여기도 `@Column(name = "paragraph_like_id")` 로 수정이 되어야 할 것 같습니다.

2023-11-09 01:05 UTC, dujong commented on src/main/java/us/usserver/like/ParagraphLike.java
> +    @Column(name = "paragraphLike_id")
수정 완료했습니다.

2023-11-09 01:05 UTC, dujong commented on src/main/java/us/usserver/like/NovelLike.java
> +    @Column(name = "novelLike_id")
수정 완료했습니다.

2023-11-09 01:05 UTC, dujong commented on src/main/java/us/usserver/authority/Authority.java
> +    @JoinColumn(name = "user_id")
수정 완료했습니다.

2023-11-09 01:42 UTC, merged